# Başlangıç ada dosyası (.schem formatı)
# EasyEdit plugin_data/EasyEdit/schematics/ klasöründe olmalı
startingIsland: "start.schem"

# Seviye veren bloklar
xpBlocks:
  cobblestone: 1
  stone: 1
  diamond_block: 50
  grass: 2
